[package]
name = "use_historical"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.20"
historical = {path = "../historical"}
firestore_hooks = {path = "../firestore_hooks"}
firestore = {path = "../firestore"}
serde = {version = "1.0"}
serde_json = {version = "1.0"}
