[package]
name = "use_historical"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
yew-router = "0.16"
historical = {path = "../historical"}
serde = {version = "1.0"}
serde_json = {version = "1.0"}
web-sys = "0.3"
wasm-bindgen = "0.2"
