[package]
name = "landing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.20"
atoms = {path = "../atoms"}
yew-router = "0.17"
router = {path = "../router"}
firestore = { path = "../firestore" }
user_id_storage = { path = "../user_id_storage" }
model = { path = "../model" }
firestore_hooks = { path = "../firestore_hooks" }
use_historical = { path = "../use_historical" }
names = { version = "0.12", default-features = false }