[package]
name = "use_can_roll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.20"
firestore_hooks = {path = "../firestore_hooks"}
use_historical = {path = "../use_historical"}
model = {path = "../model"}