[package]
name = "roleroll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "packages/presentational"
]

[dependencies]
yew = "0.19"
wasm-bindgen = "0.2"
serde_json = "1.0"
js-sys = "0.3"
serde = "1.0"
web-sys = "0.3"
presentational = {path = "./packages/presentational"}
yew-router = "0.16"