[package]
name = "roleroll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "packages/presentational",
    "packages/firestore",
]

[dependencies]
yew = "0.19"
js-sys = "0.3"
web-sys = "0.3"
presentational = {path = "./packages/presentational"}
firestore = {path = "./packages/firestore"}
yew-router = "0.16"
