[package]
name = "lobby"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.20"
atoms = {path = "../atoms"}
firestore = { path = "../firestore" }
model = { path = "../model" }
firestore_hooks = { path = "../firestore_hooks" }
layouting = { path = "../layouting" }
use_historical = { path = "../use_historical" }
web-sys = { version = "0.3" }
wasm-bindgen = "0.2"