[package]
name = "lobby"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
presentational = {path = "../presentational"}
firestore = { path = "../firestore" }
user_id_storage = { path = "../user_id_storage" }
model = { path = "../model" }
firestore_hooks = { path = "../firestore_hooks" }