[package]
name = "rule_make"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
serde_json = "1.0"
serde = "1.0"
atoms = {path = "../atoms"}
firestore = { path = "../firestore" }
model = { path = "../model" }
firestore_hooks = { path = "../firestore_hooks" }
layouting = { path = "../layouting" }
web-sys = "0.3"