[package]
name = "use_stored_input"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-sys = "0.3" 
yew = "0.20"
serde = "1.0"
serde_json= "*"