[package]
name = "roll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"
atoms = {path = "../atoms"}
firestore = { path = "../firestore" }
model = { path = "../model" }
firestore_hooks = { path = "../firestore_hooks" }
rand = { version = "0.8" }
getrandom = { version = "0.2", features = ["js"] }
layouting = { path = "../layouting" }
js-sys = "0.3"
web-sys = "0.3"
wasm-bindgen = "0.2"
use_historical = { path = "../use_historical" }