[package]
name = "app_root"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = {version="0.20"}
atoms = {path = "../atoms"}
model = {path = "../model"}
yew-router = "0.17"
router = {path = "../router"}
landing = {path = "../landing"}
lobby = {path = "../lobby"}
rule_make = {path = "../rule_make"}
roll = {path = "../roll"}
user_id_storage = {path = "../user_id_storage"}
firestore_hooks = {path = "../firestore_hooks"}
firestore = {path = "../firestore"}
web-sys = "0.3" 
use_history_state = {path = "../use_history_state"}
serde = { version = "1.0", features = ["derive"] }
use_can_roll = { path = "../use_can_roll" }